# Gradle
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Kotlin
kotlin.code.style=official
ksp.incremental=true
