import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.devtools.ksp")
    id("com.google.dagger.hilt.android")
}

// Optional signing config from keystore.properties (NOT committed)
val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) load(keystorePropertiesFile.inputStream())
}

android {
    namespace = "com.offlinetranslator.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.offlinetranslator.app"
        // Min API 26 (Android 8) — covers all Huawei Mate 10 / P20 / nova 3 onward.
        minSdk = 26
        targetSdk = 35
        versionCode = 6
        versionName = "1.0.5"

        // Restrict to ABIs that LiteRT ships. Most modern Huawei devices
        // (Mate / P / nova) are arm64-v8a; armeabi-v7a kept for older fallback.
        ndk { abiFilters += listOf("arm64-v8a", "armeabi-v7a") }

        vectorDrawables { useSupportLibrary = true }
        resourceConfigurations += listOf("zh", "en")

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // GitHub repo coordinates used by the in-app updater to query the
        // Releases API and download the latest signed APK. Keep in sync with
        // the repository this project is published to.
        buildConfigField("String", "GITHUB_OWNER", "\"chunguangwei\"")
        buildConfigField("String", "GITHUB_REPO", "\"offline-translator\"")
    }

    if (keystorePropertiesFile.exists()) {
        signingConfigs {
            create("release") {
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
            }
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
        release {
            // Keep R8 disabled for sideload distribution: avoids any reflection
            // / native-callback breakage from LiteRT-LM, and the APK is already
            // small enough (~30MB) without the model.
            isMinifyEnabled = false
            isShrinkResources = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            // Use the user-supplied release keystore if present; otherwise
            // fall back to the debug keystore so the APK is still signed and
            // installable on any phone (incl. Huawei sideload). The debug
            // keystore is generated by AGP automatically.
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs = listOf(
            "-Xjvm-default=all",
            "-opt-in=kotlin.RequiresOptIn",
            // LiteRT-LM SDK is compiled with Kotlin 2.2.x; allow our 2.0.x compiler
            // to consume its metadata.
            "-Xskip-metadata-version-check",
        )
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += setOf(
                "META-INF/{AL2.0,LGPL2.1}",
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE*",
                "META-INF/NOTICE*",
                "META-INF/INDEX.LIST",
            )
        }
        // LiteRT bundled .so files; allow duplicates if any.
        jniLibs { useLegacyPackaging = false }
    }

    androidResources {
        // We ship a hand-written locales_config.xml; no need for AGP auto-generation
        // (which would require a resources.properties file).
        generateLocaleConfig = false
    }

    lint {
        abortOnError = false
        checkReleaseBuilds = false
    }
}

dependencies {
    // Core
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.2")

    // Compose BOM
    val composeBom = platform("androidx.compose:compose-bom:2024.10.00")
    implementation(composeBom)
    androidTestImplementation(composeBom)
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.animation:animation")
    debugImplementation("androidx.compose.ui:ui-tooling")

    // Navigation
    implementation("androidx.navigation:navigation-compose:2.8.3")

    // Hilt
    implementation("com.google.dagger:hilt-android:2.57.2")
    ksp("com.google.dagger:hilt-compiler:2.57.2")
    implementation("androidx.hilt:hilt-navigation-compose:1.2.0")
    implementation("androidx.hilt:hilt-work:1.2.0")
    ksp("androidx.hilt:hilt-compiler:1.2.0")

    // DataStore
    implementation("androidx.datastore:datastore-preferences:1.1.1")

    // Room
    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // Network (model download)
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("androidx.work:work-runtime-ktx:2.9.1")

    // Serialization
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    // CameraX
    implementation("androidx.camera:camera-camera2:1.4.0")
    implementation("androidx.camera:camera-lifecycle:1.4.0")
    implementation("androidx.camera:camera-view:1.4.0")

    // Coil
    implementation("io.coil-kt:coil-compose:2.7.0")

    // LiteRT-LM Android SDK — official runtime for `.litertlm` model bundles.
    // Unlike `tasks-genai` (MediaPipe), this SDK fully supports vision/audio for
    // Gemma 4 (E2B/E4B) `.litertlm` files via Engine + Conversation + Content.
    implementation("com.google.ai.edge.litertlm:litertlm-android:0.11.0")

    // Test
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
}
